name: Deploy Calculator

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Install ESLint Recommended Configuration
        run: npm install eslint-config-eslint --save-dev

      - name: Lint HTML Files
        run: |
          npx eslint --ext .html --config eslint:recommended .
          # Adjust the eslint command based on your project structure and preferences

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: . 
